variables:
  FF_NETWORK_PER_BUILD: "true"

stages:
  - download
  - build
  - manifest

.variants:
  py313: &py313
    BASE_IMAGE: "registry.gitlab.com/thelabnyc/python:3.13@sha256:6e7af603153d59a895739dec24b7ca0c9136aefd1623abf3f1d3661d867ff1ab"
    MUTABLE_TAG_NAME: "3.13"
    IMMUTABLE_TAG_NAME: "3.13.${CI_PIPELINE_IID}"
  py314: &py314
    BASE_IMAGE: "registry.gitlab.com/thelabnyc/python:3.14@sha256:d5f5e272767535d07a13c8a817760e0c42f72e61df42c8378fddb89eedaccebc"
    MUTABLE_TAG_NAME: "3.14"
    IMMUTABLE_TAG_NAME: "3.14.${CI_PIPELINE_IID}"
  py313_node22: &py313_node22
    BASE_IMAGE: "registry.gitlab.com/thelabnyc/python:3.13-node22@sha256:7b84c93a3447c4e9cefb0b3a2a378b72fbeb987310eb1935ac7d210cbff430b3"
    MUTABLE_TAG_NAME: "3.13-node22"
    IMMUTABLE_TAG_NAME: "3.13.${CI_PIPELINE_IID}-node22"
  py313_node24: &py313_node24
    BASE_IMAGE: "registry.gitlab.com/thelabnyc/python:3.13-node24@sha256:61b288f55f4271481a4fb9d1c2dab3d558ef8238925722f0f445ad9460a42a01"
    MUTABLE_TAG_NAME: "3.13-node24"
    IMMUTABLE_TAG_NAME: "3.13.${CI_PIPELINE_IID}-node24"
  py314_node24: &py314_node24
    BASE_IMAGE: "registry.gitlab.com/thelabnyc/python:3.14-node24@sha256:bc3d03c6df78ae1997548ab87bd83f2b16fb8171b4f2c7139afecee9441bdccf"
    MUTABLE_TAG_NAME: "3.14-node24"
    IMMUTABLE_TAG_NAME: "3.14.${CI_PIPELINE_IID}-node24"

.base_job: &base_job
  rules:
    - if: '$CI_PIPELINE_SOURCE == "merge_request_event"'
      variables:
        TAG_SUFFIX: "-mr${CI_MERGE_REQUEST_IID}"
    # No suffix for default branch
    - if: $CI_COMMIT_BRANCH == $CI_DEFAULT_BRANCH && $CI_COMMIT_REF_PROTECTED == "true"
      variables:
        TAG_SUFFIX: ""

download_db:
  <<: *base_job
  stage: download
  image: ubuntu:latest@sha256:84e77dee7d1bc93fb029a45e3c6cb9d8aa4831ccfcc7103d36e876938d28895b
  tags:
    - thelab-arm64
  script:
    - apt-get update
    - apt-get install -y wget
    - mkdir -p ./data
    - wget "https://download.maxmind.com/app/geoip_download?edition_id=GeoLite2-Country&license_key=$MAXMIND_LICENSE_KEY&suffix=tar.gz" -O "data/GeoLite2-Country.mmdb.tar.gz"
    - wget "https://download.maxmind.com/app/geoip_download?edition_id=GeoLite2-City&license_key=$MAXMIND_LICENSE_KEY&suffix=tar.gz" -O "data/GeoLite2-City.mmdb.tar.gz"
  artifacts:
    paths:
      - data/*

build:
  <<: *base_job
  stage: build
  needs:
    - job: download_db
      artifacts: true
  tags:
    - $RUNNER_TAG
  script:
    - docker login -u "${CI_REGISTRY_USER}" -p "${CI_JOB_TOKEN}" "${CI_REGISTRY}"
    - ./bin/build.sh
  parallel:
    matrix:
      - <<: *py313
        ARCH: amd64
        RUNNER_TAG: thelab-amd64
      - <<: *py313
        ARCH: arm64
        RUNNER_TAG: thelab-arm64
      - <<: *py314
        ARCH: amd64
        RUNNER_TAG: thelab-amd64
      - <<: *py314
        ARCH: arm64
        RUNNER_TAG: thelab-arm64
      - <<: *py313_node22
        ARCH: amd64
        RUNNER_TAG: thelab-amd64
      - <<: *py313_node22
        ARCH: arm64
        RUNNER_TAG: thelab-arm64
      - <<: *py313_node24
        ARCH: amd64
        RUNNER_TAG: thelab-amd64
      - <<: *py313_node24
        ARCH: arm64
        RUNNER_TAG: thelab-arm64
      - <<: *py314_node24
        ARCH: amd64
        RUNNER_TAG: thelab-amd64
      - <<: *py314_node24
        ARCH: arm64
        RUNNER_TAG: thelab-arm64

manifest:
  stage: manifest
  needs: [build]
  tags:
    - thelab-arm64
  image: docker:latest@sha256:f80c26212befc1c1988b529495532c6b9180d9b1dab1611f4a1efbe9da8ec821
  rules:
    - if: $CI_COMMIT_BRANCH == $CI_DEFAULT_BRANCH && $CI_COMMIT_REF_PROTECTED == "true"
  script:
    - apk add bash
    - docker login -u "${CI_REGISTRY_USER}" -p "${CI_JOB_TOKEN}" "${CI_REGISTRY}"
    - ./bin/push-manifest.sh
  parallel:
    matrix:
      - <<: *py313
      - <<: *py314
      - <<: *py313_node22
      - <<: *py313_node24
      - <<: *py314_node24
