variables:
  FF_NETWORK_PER_BUILD: "true"

stages:
  - download
  - build
  - manifest

.variants:
  py313: &py313
    BASE_IMAGE: "registry.gitlab.com/thelabnyc/python:3.13@sha256:8c591680d9d82a7a5c81a127c68f40ce9ea736fb48cfd0791d7db8b89acb33f0"
    MUTABLE_TAG_NAME: "3.13"
    IMMUTABLE_TAG_NAME: "3.13.${CI_PIPELINE_IID}"
  py314: &py314
    BASE_IMAGE: "registry.gitlab.com/thelabnyc/python:3.14@sha256:d3dae5607394565c6393500d7f59a9a0ba8bfacea17097df9ad5bcc6f75f2019"
    MUTABLE_TAG_NAME: "3.14"
    IMMUTABLE_TAG_NAME: "3.14.${CI_PIPELINE_IID}"
  py313_node22: &py313_node22
    BASE_IMAGE: "registry.gitlab.com/thelabnyc/python:3.13-node22@sha256:a2878dcb96e06c80363a04fbef796db51da86dfc6497683e3266700435de4676"
    MUTABLE_TAG_NAME: "3.13-node22"
    IMMUTABLE_TAG_NAME: "3.13.${CI_PIPELINE_IID}-node22"
  py313_node24: &py313_node24
    BASE_IMAGE: "registry.gitlab.com/thelabnyc/python:3.13-node24@sha256:ac804e0dac1673b8cf9357555f8b2de59ce7e59f0441bede670649a8a7222732"
    MUTABLE_TAG_NAME: "3.13-node24"
    IMMUTABLE_TAG_NAME: "3.13.${CI_PIPELINE_IID}-node24"
  py314_node24: &py314_node24
    BASE_IMAGE: "registry.gitlab.com/thelabnyc/python:3.14-node24@sha256:b3846255e1ccdebb1c3b7bd20a36cee7f9be9b0a16ae672926144416723b4e6b"
    MUTABLE_TAG_NAME: "3.14-node24"
    IMMUTABLE_TAG_NAME: "3.14.${CI_PIPELINE_IID}-node24"

.base_job: &base_job
  rules:
    - if: '$CI_PIPELINE_SOURCE == "merge_request_event"'
      variables:
        TAG_SUFFIX: "-mr${CI_MERGE_REQUEST_IID}"
    # No suffix for default branch
    - if: $CI_COMMIT_BRANCH == $CI_DEFAULT_BRANCH && $CI_COMMIT_REF_PROTECTED == "true"
      variables:
        TAG_SUFFIX: ""

download_db:
  <<: *base_job
  stage: download
  image: ubuntu:latest@sha256:d1e2e92c075e5ca139d51a140fff46f84315c0fdce203eab2807c7e495eff4f9
  tags:
    - thelab-arm64
  script:
    - apt-get update
    - apt-get install -y wget
    - mkdir -p ./data
    - wget "https://download.maxmind.com/app/geoip_download?edition_id=GeoLite2-Country&license_key=$MAXMIND_LICENSE_KEY&suffix=tar.gz" -O "data/GeoLite2-Country.mmdb.tar.gz"
    - wget "https://download.maxmind.com/app/geoip_download?edition_id=GeoLite2-City&license_key=$MAXMIND_LICENSE_KEY&suffix=tar.gz" -O "data/GeoLite2-City.mmdb.tar.gz"
  artifacts:
    paths:
      - data/*

build:
  <<: *base_job
  stage: build
  needs:
    - job: download_db
      artifacts: true
  tags:
    - $RUNNER_TAG
  script:
    - docker login -u "${CI_REGISTRY_USER}" -p "${CI_JOB_TOKEN}" "${CI_REGISTRY}"
    - ./bin/build.sh
  parallel:
    matrix:
      - <<: *py313
        ARCH: amd64
        RUNNER_TAG: thelab-amd64
      - <<: *py313
        ARCH: arm64
        RUNNER_TAG: thelab-arm64
      - <<: *py314
        ARCH: amd64
        RUNNER_TAG: thelab-amd64
      - <<: *py314
        ARCH: arm64
        RUNNER_TAG: thelab-arm64
      - <<: *py313_node22
        ARCH: amd64
        RUNNER_TAG: thelab-amd64
      - <<: *py313_node22
        ARCH: arm64
        RUNNER_TAG: thelab-arm64
      - <<: *py313_node24
        ARCH: amd64
        RUNNER_TAG: thelab-amd64
      - <<: *py313_node24
        ARCH: arm64
        RUNNER_TAG: thelab-arm64
      - <<: *py314_node24
        ARCH: amd64
        RUNNER_TAG: thelab-amd64
      - <<: *py314_node24
        ARCH: arm64
        RUNNER_TAG: thelab-arm64

manifest:
  stage: manifest
  needs: [build]
  tags:
    - thelab-arm64
  image: docker:latest@sha256:68f6d9ab84623d1116c5432a3b924a07ee09960e6129ca1cb03ef14010588cb4
  rules:
    - if: $CI_COMMIT_BRANCH == $CI_DEFAULT_BRANCH && $CI_COMMIT_REF_PROTECTED == "true"
  script:
    - apk add bash
    - docker login -u "${CI_REGISTRY_USER}" -p "${CI_JOB_TOKEN}" "${CI_REGISTRY}"
    - ./bin/push-manifest.sh
  parallel:
    matrix:
      - <<: *py313
      - <<: *py314
      - <<: *py313_node22
      - <<: *py313_node24
      - <<: *py314_node24
