variables:
  FF_NETWORK_PER_BUILD: "true"

stages:
  - download
  - build
  - manifest

.variants:
  py313: &py313
    BASE_IMAGE: "registry.gitlab.com/thelabnyc/python:3.13@sha256:c637f1fff543a64d3f4a444e011d8d3b946fd10c417a5009f5eec925a7406a5b"
    MUTABLE_TAG_NAME: "3.13"
    IMMUTABLE_TAG_NAME: "3.13.${CI_PIPELINE_IID}"
  py314: &py314
    BASE_IMAGE: "registry.gitlab.com/thelabnyc/python:3.14@sha256:ab831a06a29a37bb133444e7f151563f4e0f5e2caf23359cd8076a09be5a510c"
    MUTABLE_TAG_NAME: "3.14"
    IMMUTABLE_TAG_NAME: "3.14.${CI_PIPELINE_IID}"
  py313_node22: &py313_node22
    BASE_IMAGE: "registry.gitlab.com/thelabnyc/python:3.13-node22@sha256:249b5ee46322b23353238cc7a4d48434160f95e01364ef668fb4ac6d386acd4e"
    MUTABLE_TAG_NAME: "3.13-node22"
    IMMUTABLE_TAG_NAME: "3.13.${CI_PIPELINE_IID}-node22"
  py313_node24: &py313_node24
    BASE_IMAGE: "registry.gitlab.com/thelabnyc/python:3.13-node24@sha256:ff05ba006a21b1376b9dcde1d8f10ec79d5b02c49bb77e2de6a430d80e9da500"
    MUTABLE_TAG_NAME: "3.13-node24"
    IMMUTABLE_TAG_NAME: "3.13.${CI_PIPELINE_IID}-node24"
  py314_node24: &py314_node24
    BASE_IMAGE: "registry.gitlab.com/thelabnyc/python:3.14-node24@sha256:cf65edf6bbe1644cc66d1c8d7d09033bb9407b7ecfd233daa1e322af0e0a4967"
    MUTABLE_TAG_NAME: "3.14-node24"
    IMMUTABLE_TAG_NAME: "3.14.${CI_PIPELINE_IID}-node24"

.base_job: &base_job
  rules:
    - if: '$CI_PIPELINE_SOURCE == "merge_request_event"'
      variables:
        TAG_SUFFIX: "-mr${CI_MERGE_REQUEST_IID}"
    # No suffix for default branch
    - if: $CI_COMMIT_BRANCH == $CI_DEFAULT_BRANCH && $CI_COMMIT_REF_PROTECTED == "true"
      variables:
        TAG_SUFFIX: ""

download_db:
  <<: *base_job
  stage: download
  image: ubuntu:latest@sha256:0d39fcc8335d6d74d5502f6df2d30119ff4790ebbb60b364818d5112d9e3e932
  tags:
    - thelab-arm64
  script:
    - apt-get update
    - apt-get install -y wget
    - mkdir -p ./data
    - wget "https://download.maxmind.com/app/geoip_download?edition_id=GeoLite2-Country&license_key=$MAXMIND_LICENSE_KEY&suffix=tar.gz" -O "data/GeoLite2-Country.mmdb.tar.gz"
    - wget "https://download.maxmind.com/app/geoip_download?edition_id=GeoLite2-City&license_key=$MAXMIND_LICENSE_KEY&suffix=tar.gz" -O "data/GeoLite2-City.mmdb.tar.gz"
  artifacts:
    paths:
      - data/*

build:
  <<: *base_job
  stage: build
  needs:
    - job: download_db
      artifacts: true
  tags:
    - $RUNNER_TAG
  script:
    - docker login -u "${CI_REGISTRY_USER}" -p "${CI_JOB_TOKEN}" "${CI_REGISTRY}"
    - ./bin/build.sh
  parallel:
    matrix:
      - <<: *py313
        ARCH: amd64
        RUNNER_TAG: thelab-amd64
      - <<: *py313
        ARCH: arm64
        RUNNER_TAG: thelab-arm64
      - <<: *py314
        ARCH: amd64
        RUNNER_TAG: thelab-amd64
      - <<: *py314
        ARCH: arm64
        RUNNER_TAG: thelab-arm64
      - <<: *py313_node22
        ARCH: amd64
        RUNNER_TAG: thelab-amd64
      - <<: *py313_node22
        ARCH: arm64
        RUNNER_TAG: thelab-arm64
      - <<: *py313_node24
        ARCH: amd64
        RUNNER_TAG: thelab-amd64
      - <<: *py313_node24
        ARCH: arm64
        RUNNER_TAG: thelab-arm64
      - <<: *py314_node24
        ARCH: amd64
        RUNNER_TAG: thelab-amd64
      - <<: *py314_node24
        ARCH: arm64
        RUNNER_TAG: thelab-arm64

manifest:
  stage: manifest
  needs: [build]
  tags:
    - thelab-arm64
  image: docker:latest@sha256:1ba18449911d01f477a3fc104123c85d677addc60701b14b3fcb5381f9c4a537
  rules:
    - if: $CI_COMMIT_BRANCH == $CI_DEFAULT_BRANCH && $CI_COMMIT_REF_PROTECTED == "true"
  script:
    - apk add bash
    - docker login -u "${CI_REGISTRY_USER}" -p "${CI_JOB_TOKEN}" "${CI_REGISTRY}"
    - ./bin/push-manifest.sh
  parallel:
    matrix:
      - <<: *py313
      - <<: *py314
      - <<: *py313_node22
      - <<: *py313_node24
      - <<: *py314_node24
